// Generated by CoffeeScript 1.6.3
(function() {
  window.GitLab = function(host, token) {
    var settings;
    this.Model = Backbone.Model.extend();
    this.Collection = Backbone.Collection.extend();
    settings = {
      host: host,
      token: token
    };
    return {
      User: this.Model.extend(),
      Users: this.Collection.extend(),
      Project: this.Model.extend(),
      Projects: this.Collection.extend()
    };
  };

}).call(this);
